Sync with zshdb.

diff --git a/kshdb.in b/kshdb.in
--- a/kshdb.in
+++ b/kshdb.in
@@ -33,11 +33,19 @@ typeset _Dbg_orig_0=$0
 # Equivalent to basename $0; the short program name
 typeset _Dbg_pname=${0##*/}  
 
+## Stuff set by autoconf/configure ###
 typeset prefix=@prefix@
 typeset _Dbg_libdir=@PKGDATADIR@
+###
 
 # Name we refer to ourselves by
 typeset _Dbg_debugger_name='@PACKAGE@'
+
+# The shell we are configured to run under.
+typeset _Dbg_shell='@SH_PROG@'
+
+# The short shell name. Helps keep code common in bash, zsh, and ksh debuggers.
+typeset _Dbg_shell_name=${_Dbg_shell##*/}  # Equivalent to basename(_Dbg_shell)
 
 # Parse just the libdir option
 typeset -i i
@@ -67,9 +75,9 @@ fi
 typeset _Dbg_main="$_Dbg_libdir/dbg-main.sh"
 if [[ ! -r $_Dbg_main ]] ; then 
   print "${_Dbg_pname}: Can't read debugger library file '${_Dbg_main}'."
-  print "${_Dbg_pname}: Perhaps kshdb is installed wrong (if its installed)." >&2
-  print "${_Dbg_pname}: Try running kshdb using -L (with a different directory)." >&2
-  print "${_Dbg_pname}: Run kshdb --help for a list and explanation of options." >&2
+  print "${_Dbg_pname}: Perhaps @PACKAGE@ is installed wrong (if its installed)." >&2
+  print "${_Dbg_pname}: Try running @PACKAGE@ using -L (with a different directory)." >&2
+  print "${_Dbg_pname}: Run @PACKAGE@ --help for a list and explanation of options." >&2
   exit 1
 fi
 
@@ -80,15 +88,23 @@ _Dbg_set_debugger_entry
 # Note that this is called via kshdb rather than "ksh --debugger" or kshdb-trace
 _Dbg_script=1
 
-# TEMPORARY: Save me typing in testing.
+if [[ -n $_Dbg_EXECUTION_STRING ]] ; then
+    _Dbg_script_file=$(_Dbg_tempname cmd)
+    echo "$_Dbg_EXECUTION_STRING" >$_Dbg_script_file
+fi
+
 if (( ${#_Dbg_script_args[@]} > 0 )) ; then
-    _Dbg_script_file="$_Dbg_script_args[0]"
+    _Dbg_script_file="${_Dbg_script_args[0]}"
     # FIXME: 
     # shift _Dbg_script_args
-else
-    _Dbg_script_file=./testing.sh
-    # _Dbg_script_file=./file2.sh
-    _Dbg_script_args=($_Dbg_script_file)
+elif [[ -z $_Dbg_EXECUTION_STRING ]] ; then
+    echo >&2 "${_Dbg_pname}: need to give a script to debug or use the -c option."
+    exit 1
+fi
+
+if [[ ! -r "$_Dbg_script_file" ]] ; then
+  echo "${_Dbg_pname}: cannot read program to debug: $_Dbg_script_file." >&2
+  exit 1
 fi
 
 _Dbg_step_ignore=2
